from app import db
from datetime import datetime
class Alert(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    identifier = db.Column(db.String(36), unique=True)
    source_ip = db.Column(db.String(45))
    destination_ip = db.Column(db.String(45))
    source_port = db.Column(db.Integer)
    destination_port = db.Column(db.Integer)
    protocol = db.Column(db.String(10))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    alert_type = db.Column(db.String(50))
    event_id = db.Column(db.String(36))
    payload = db.Column(db.Text)
    user_agent = db.Column(db.String(255))
    action_taken = db.Column(db.String(50))
    signature_id = db.Column(db.String(50))
    severity = db.Column(db.String(20))
    event_description = db.Column(db.Text)
    intrusion_type = db.Column(db.String(50))
    file_hash = db.Column(db.String(64))
    payload_length = db.Column(db.Integer)
    protocol_flags = db.Column(db.String(50))
    connection_id = db.Column(db.String(36))
    alert_message = db.Column(db.Text)
    flow_direction = db.Column(db.String(20))
    alert_category = db.Column(db.String(50))
    source_mac = db.Column(db.String(17))
    destination_mac = db.Column(db.String(17))
    host_name = db.Column(db.String(255))
    geolocation = db.Column(db.String(100))
    bytes_transferred = db.Column(db.Integer)
    packet_count = db.Column(db.Integer)
    application_layer_data = db.Column(db.Text)
    alert_source = db.Column(db.String(50))
    hostname_source = db.Column(db.String(255))
    hostname_destination = db.Column(db.String(255))
